package udwRspBuilderLib

import (
	"bytes"
	"github.com/tachyon-protocol/udw/udwGoSource/udwGoParser"
	"github.com/tachyon-protocol/udw/udwGoSource/udwGoWriter"
	"strconv"
)

type GoBuilderCtx struct {
	Req              GoBuilderCtxRequest
	GoFileContext    *udwGoWriter.GoFileContext
	GoFileBuffer     bytes.Buffer
	GoFileHBuffer    bytes.Buffer
	GoFileFuncBuffer bytes.Buffer

	CurrentProcessFnName string

	nextVarId int

	seenMarshalNamedStructMap   map[string]bool
	seenUnmarshalNamedStructMap map[string]bool
}

type GoFnVisitor func(f func(fnDef *udwGoParser.FuncOrMethodDeclaration))

type GoBuilderCtxRequest struct {
	OutGoFilePath                 string
	CgoHeaderContent              string
	IsNoParameterFromGoDirectCall bool
	IsStringUTF16                 bool
	PkgImportPath                 string
	BuildFlagContent              string

	GoToJavaDispatchPackage string
	GjNameIdGetter          func(fn *udwGoParser.FuncOrMethodDeclaration) string
}

func NewGoBuilderCtx(req GoBuilderCtxRequest) *GoBuilderCtx {
	ctx := &GoBuilderCtx{}
	ctx.Req = req
	ctx.GoFileContext = udwGoWriter.NewGoFileContext(req.PkgImportPath)
	ctx.seenMarshalNamedStructMap = map[string]bool{}
	ctx.seenUnmarshalNamedStructMap = map[string]bool{}
	return ctx
}

func (ctx *GoBuilderCtx) GetNextVarString() string {
	ctx.nextVarId++
	return "_var" + strconv.Itoa(ctx.nextVarId)
}

func (ctx *GoBuilderCtx) GetFromGoCFnPrototypeContent(cFnName string) string {
	return `udwGaoc_c_PAndC ` + cFnName + `(uint8_t* _pIn,size_t _cIn)`
}

func (ctx *GoBuilderCtx) GenGo(toGoFn GoFnVisitor, fromGoFn GoFnVisitor) {
	toGoFn(func(fnDef *udwGoParser.FuncOrMethodDeclaration) {
		ctx.ToGoGenFnGoFile(fnDef)
	})
	fromGoFn(func(fnDef *udwGoParser.FuncOrMethodDeclaration) {
		ctx.FromGoGenFnGoFile(fnDef)
	})
	fileBuffer := bytes.Buffer{}
	ctx.GoFileContext.SetBuildFlagContent(ctx.Req.BuildFlagContent)
	fileBuffer.WriteString(`//// Auto generated by udwRspBuilderLib , do not edit it.

/*
` + ctx.Req.CgoHeaderContent + `

#include "src/github.com/tachyon-protocol/udw/udwRpc/udwRpcSameProcess/udwRspLib/udwRspLib.h"

` + ctx.GoFileHBuffer.String() + `
 */
import "C"
` + ctx.GoFileBuffer.String() + "\n" + ctx.GoFileFuncBuffer.String())
	ctx.GoFileContext.MustWriteFile(ctx.Req.OutGoFilePath, fileBuffer.Bytes())
}
